### ISSUE TITLE
Example demo broken?

### ISSUE THREAD

**Issue by martinlutter** [kwebio/docs#7]
Hi, I noticed you have a demo available which should show some of Kweb's features.
But the todo list is empty.
![Screenshot from 2020-03-05 17-36-17](https://user-images.githubusercontent.com/19926144/76003214-0535a400-5f08-11ea-8424-c3d923c4fb9e.png)
Also clicking the two links at the top just redirects me back to the demo.
I used Firefox 73.0.1 (64-bit) on Ubuntu.

I'd also like to ask a question - is it possible to not use any inline Javascript or eval(), at all?
So that I wouldn't have to allow `unsafe-inline` and `unsafe-eval` when configuring CSP.
Thank you.

**Comment by fklappan** [comment]
Is the demo still broken or again?

**Comment by DineshSolanki** [comment]
[http://demo.kweb.io](http://demo.kweb.io) this is working fine, but its not ToDoList Demo

**Comment by sanity** [comment]
Looks like this is fixed.
